### ISSUE TITLE
Diplomitöö hetkeseis

### ISSUE THREAD

**Issue by mrtrvl** [TLUHK-RIF21/Jane-Milvek#1]
Palun anna mulle paari lausega ülevaade oma diplomitöö hetkeseisust:
- kõik on hästi
- vajan abi
- ei ole veel alustanud
- ei ole juhendajat/ei saa juhendajaga ühendust
- ei oska midagi teah
- ...

**Comment by JaneMilvek** [comment]
@mrtrvl Diplomitööga on väike algus tehtud ning järgneva nädala jooksul plaanis jõudsamalt ette võtta. Idee on olemas kuidas edasi liikuda.

**Comment by mrtrvl** [comment]
Kas oled juhendajaga ka suhelnud?

**Comment by JaneMilvek** [comment]
Hetkel veel ei ole, aga plaanin uue nädala alguses, kui süvenema hakkan teemasse jälle.
