### ISSUE TITLE
🔔  Diplomitöö mustandi esitamise tähtaeg 🔔

### ISSUE THREAD

**Issue by mrtrvl** [TLUHK-RIF21/Jane-Milvek#2]
Tuletan meelde diplomitöö mustandi esitamise tähtaega, mis on **05. märts kell 09:00**.

Esita link oma diplomitöö mustandile vastates sellele `Issue`-le.

❗ Esita oma mustand ka juhul, kui seal on sisu väga vähe või kui sisu on väga kaootiline.❗

**Comment by JaneMilvek** [comment]
Lisan lingi oma lõputöö algusele: [link](https://docs.google.com/document/d/1BOI2z78Ykf9Xozp8gq-aVynOKbVDT1Gi/edit?usp=sharing&ouid=107258591353822615176&rtpof=true&sd=true)
Hetkel materjalide kogumise ja enda jaoks küsimuste läbimõtlemise faas.

**Comment by mrtrvl** [comment]
Proovi nüüd kohe alguses hakata järgima enam-vähem diplomitöö struktuuri, nagu on siin kirjeldatud: https://docs.google.com/document/d/1-JdwM9h8zngLyVuKqQpFRGthL50ySc4vbHIpBWuE__g/edit

Pane kirja probleem, uurimisküsimused, uurimistegevused ja sealt edasi.
