### ISSUE TITLE
🔔Järgmine diplomitöö mustandi esitamise tähtaeg 🔔

### ISSUE THREAD

**Issue by mrtrvl** [TLUHK-RIF21/Jane-Milvek#3]
Järgmine diplomitöö mustandi esitamise tähtaeg on **09. aprill kell 09:00**.

Esita link oma diplomitöö mustandile vastates sellele `Issue`-le (võib ka varem esitada :smile: )

**Comment by JaneMilvek** [comment]
Natuke alguses veel kirjutamine ja palju sisulist osa eelmisest korrast juurde ei ole tulnud. Võtsin arvesse sinu ja Laura soovitusi ning korrastasin olemasolevat infot: [link](https://docs.google.com/document/d/1BOI2z78Ykf9Xozp8gq-aVynOKbVDT1Gi/edit?usp=sharing&ouid=107258591353822615176&rtpof=true&sd=true)
Tegelesin ka materjali otsimise ja järgmiste sammude läbimõtlemisega.

**Comment by mrtrvl** [comment]
Hetkel ühtegi kommentaari ei lisanud. Nüüd on kindlasti viimane aeg hakata hooga sisu tootma.
Palun suhtle oma juhendajaga ka, sest ma saan aru, et ta ei tea hetkel Sinu plaanidest ja tegemistest midagi.
